"""Renders the three generated Markdown artifacts.

Expected ``context`` dict shape (built by ``worker/job_processor.py``):

    {
      "app_record": worker.models.Application,
      "normalized": dict,          # current normalized snapshot
      "diff": dict,                 # structured diff model
      "impact": dict,                # output of analyze_documentation_impact
      "from_version": str | None,
      "to_version": str,
      "adapter_label": str,          # e.g. "MockCopilotAdapter" — for the
                                      # Known Limitations / provenance note
    }
"""

from __future__ import annotations

_COMPONENT_LABELS = {
    "flow": "flow",
    "screen": "screen",
    "application": "app",
    "environment_variable": "environment variable",
    "connection_reference": "connection reference",
    "dependency": "dependency",
    "security_role": "security role",
    "component": "component",
    "table": "table",
    "solution": "solution",
}


def _section(title: str, body: str) -> str:
    body = body.strip() or "Not applicable."
    return f"## {title}\n\n{body}\n\n"


def _bullet_list(items: list[str]) -> str:
    if not items:
        return ""
    return "\n".join(f"- {item}" for item in items)


def _describe_change(change: dict) -> str:
    label = _COMPONENT_LABELS.get(change["component"], change["component"])
    name = change["name"]
    if change["type"] == "ADDED":
        return f'Added {label} "{name}"'
    if change["type"] == "REMOVED":
        return f'Removed {label} "{name}"'
    details = "; ".join(change.get("details", [])) or "no further detail recorded"
    return f'Changed {label} "{name}": {details}'


def render_technical_documentation(context: dict) -> str:
    app = context["app_record"]
    normalized = context["normalized"]
    solution = normalized["solution"]
    impact = context["impact"]

    out = f"# Technical Documentation — {app.title}\n\n"
    out += (
        f"_Documentation version {context['to_version']}"
        f"{' (from ' + context['from_version'] + ')' if context.get('from_version') else ' (initial)'}"
        f", generated by {context.get('adapter_label', 'unknown adapter')}._\n\n"
    )

    out += _section(
        "Overview",
        f"**Solution:** {solution['name']} (v{solution['version']})\n\n"
        f"**Publisher:** {solution['publisher']}\n\n"
        f"**Description:** {solution['description']}\n\n"
        f"**Environment:** {app.environment}",
    )

    out += _section(
        "Architecture",
        f"{len(normalized['applications'])} canvas app(s), {len(normalized['flows'])} flow(s), "
        f"{len(normalized['tables'])} table(s). See ARCHITECTURE.md in the project repository for "
        "the overall system design this application participates in (if applicable).",
    )

    component_lines = [f"{c['name']} ({c['type']})" for c in normalized["components"]]
    out += _section("Components", _bullet_list(component_lines))

    app_lines = []
    for canvas_app in normalized["applications"]:
        screens = ", ".join(s["name"] for s in canvas_app["screens"]) or "no screens recorded"
        app_lines.append(f"**{canvas_app['name']}** ({canvas_app['type']}) — screens: {screens}")
    out += _section("Power Apps", "\n\n".join(app_lines))

    flow_lines = []
    for flow in normalized["flows"]:
        flow_lines.append(
            f"**{flow['name']}**\n"
            f"- Trigger: {flow['trigger']}\n"
            f"- Actions: {', '.join(flow['actions']) or 'none recorded'}\n"
            f"- Conditions: {', '.join(flow['conditions']) or 'none recorded'}\n"
            f"- Timeout: {flow['timeout'] or 'n/a'}"
        )
    out += _section("Power Automate", "\n\n".join(flow_lines))

    data_source_lines = [f"{t['name']} ({t['type']})" for t in normalized["tables"]]
    if not data_source_lines:
        data_source_lines = [
            f"{c['name']} via {c['connector']}" for c in normalized["connection_references"]
        ]
    out += _section("Data Sources", _bullet_list(data_source_lines))

    out += _section(
        "Dependencies",
        _bullet_list([f"{d['name']} ({d['type']})" for d in normalized["dependencies"]]),
    )

    out += _section(
        "Environment Variables",
        _bullet_list(
            [
                f"{v['name']} ({v['type']}) — default: {v['default_value']}"
                for v in normalized["environment_variables"]
            ]
        ),
    )

    out += _section(
        "Connection References",
        _bullet_list(
            [f"{c['name']} — {c['connector']}" for c in normalized["connection_references"]]
        ),
    )

    out += _section("Security", _bullet_list(normalized["security"]["roles"]))

    business_logic_lines = [
        f"{flow['name']}: {', '.join(flow['conditions']) or 'no conditional branches recorded'}"
        for flow in normalized["flows"]
    ]
    out += _section("Business Logic", _bullet_list(business_logic_lines))

    error_handling_lines = [
        f"{flow['name']}: {a}"
        for flow in normalized["flows"]
        for a in flow["actions"]
        if any(k in a.lower() for k in ("error", "retry", "log", "fail"))
    ]
    out += _section(
        "Error Handling",
        _bullet_list(error_handling_lines)
        or "No explicit error-handling actions were detected in the normalized representation.",
    )

    out += _section(
        "ALM",
        f"This application is packaged as Power Platform solution '{solution['name']}' "
        f"(v{solution['version']}). Promotion between environments follows standard "
        "solution export/import; see docs/POWER_PLATFORM_SETUP.md.",
    )

    out += _section(
        "Deployment",
        f"Current environment: {app.environment} ({app.environment_url or '<environment URL pending corporate configuration>'}).",
    )

    limitations = [
        f"Overall technical impact of this update: {impact['technical_impact']}.",
        f"Overall user-facing impact of this update: {impact['user_impact']}.",
        f"Generated via {context.get('adapter_label', 'unknown adapter')} — see docs/COPILOT_INTEGRATION.md "
        "for what a real Copilot-refined pass would add.",
    ]
    out += _section("Known Limitations", _bullet_list(limitations))

    return out


def render_user_guide(context: dict) -> str:
    app = context["app_record"]
    normalized = context["normalized"]
    solution = normalized["solution"]

    out = f"# User Guide — {app.title}\n\n"
    out += _section("Purpose", solution["description"] or f"{app.title} is a Power Platform application.")

    roles = normalized["security"]["roles"]
    out += _section(
        "Who should use this application",
        _bullet_list(roles) or "Any user with access granted by the application owner.",
    )

    out += _section(
        "How to open it",
        f"Open the '{app.title}' app from Power Apps (environment: {app.environment}). "
        f"{('Direct link: ' + app.environment_url) if app.environment_url else 'Ask your administrator for the direct link.'}",
    )

    workflow_lines = [
        f"{flow['name']} — starts when: {flow['trigger']}" for flow in normalized["flows"]
    ]
    out += _section("Main workflows", _bullet_list(workflow_lines))

    steps = []
    for canvas_app in normalized["applications"]:
        for i, screen in enumerate(canvas_app["screens"], start=1):
            steps.append(f"{screen['name']}: {screen['controls_summary'] or 'no description recorded'}")
    out += _section("Step-by-step usage", _bullet_list(steps))

    expected_behavior_lines = []
    for flow in normalized["flows"]:
        for condition in flow["conditions"]:
            expected_behavior_lines.append(f"{flow['name']}: {condition}")
    out += _section(
        "Expected behavior",
        _bullet_list(expected_behavior_lines) or "The application behaves as described in Main workflows above.",
    )

    out += _section(
        "Troubleshooting",
        f"If something doesn't behave as expected, contact the application owner ({app.owner or '<owner unset>'}) "
        f"or business owner ({app.business_owner or '<business owner unset>'}). Check the DocumentationJobs list "
        "for any failed jobs related to this application.",
    )

    out += _section(
        "FAQ",
        "**Q: Where do I request a new role or access?**\nA: Contact the business owner listed above.\n\n"
        "**Q: Where can I see what changed in the latest version?**\nA: See the change summary for "
        f"version {context['to_version']} in the DocumentationVersions list.",
    )

    return out


def render_change_summary(context: dict) -> str:
    diff = context["diff"]
    lines = [_describe_change(c) for c in diff["changes"]]
    header = f"Version: {context['to_version']}"
    if context.get("from_version"):
        header += f" (previous: {context['from_version']})"
    if not lines:
        return f"{header}\n\nChanges:\n- No functional changes detected.\n"
    body = "\n".join(f"- {line}" for line in lines)
    return f"{header}\n\nChanges:\n{body}\n"
