"""MOCKED CopilotAdapter.

Deterministic, template-based generation with zero network calls — reuses
the same renderers a future ``RealCopilotAdapter`` could fall back on. Used
for local development and in tests. Never claims to be AI-generated content;
every artifact is clearly labeled as mock output.
"""

from __future__ import annotations

from worker.documentation.generator import (
    render_change_summary,
    render_technical_documentation,
    render_user_guide,
)

from .base import CopilotAdapter

_MOCK_NOTE = (
    "\n---\n_This document was generated by MockCopilotAdapter: deterministic, "
    "template-based output with no AI involvement. It exists so the pipeline is "
    "fully testable offline — see docs/COPILOT_INTEGRATION.md for the real "
    "Copilot integration plan._\n"
)


class MockCopilotAdapter(CopilotAdapter):
    def analyze_changes(self, diff: dict, deterministic_impact: dict) -> dict:
        return deterministic_impact

    def generate_technical_documentation(self, context: dict) -> str:
        context = {**context, "adapter_label": "MockCopilotAdapter"}
        return render_technical_documentation(context) + _MOCK_NOTE

    def generate_user_documentation(self, context: dict) -> str:
        context = {**context, "adapter_label": "MockCopilotAdapter"}
        return render_user_guide(context) + _MOCK_NOTE

    def generate_change_summary(self, context: dict) -> str:
        context = {**context, "adapter_label": "MockCopilotAdapter"}
        return render_change_summary(context) + _MOCK_NOTE
